"""add_dream_models

Revision ID: 71174be6e2f5
Revises: a5daccdecb55
Create Date: 2026-02-06 23:16:13.285180

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71174be6e2f5'
down_revision: str | None = 'a5daccdecb55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.Enum('NORMAL', 'LUCID', 'NIGHTMARE', 'RECURRING', 'SYMBOLIC', 'VIVID', name='dream_type_enum'), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_emoji', sa.String(length=10), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_types_type_name'), 'dream_types', ['type_name'], unique=True)
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PERSON', 'PLACE', 'OBJECT', 'ACTION', 'EMOTION', 'ABSTRACT', name='symbol_category'), nullable=False),
    sa.Column('cognitive_meaning', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_emotion_intensity', sa.Float(), nullable=True),
    sa.Column('common_emotions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=True)
    op.create_table('triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'ACTIVITY', 'EMOTION', 'ENVIRONMENT', 'SUBSTANCE', name='trigger_category'), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('nightmare_correlation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_trigger_key'), 'triggers', ['trigger_key'], unique=True)
    op.create_table('dreams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('title_generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('dream_date', sa.Date(), nullable=False),
    sa.Column('dream_time', sa.Time(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awakening_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_nap', sa.Boolean(), nullable=False),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('awakening_state', sa.Enum('NATURAL', 'ALARM', 'STARTLED', 'GRADUAL', name='awakening_state'), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_fragmented', sa.Boolean(), nullable=True),
    sa.Column('sleep_depth', sa.SmallInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('completeness_score', sa.SmallInteger(), nullable=True),
    sa.Column('primary_emotion', sa.String(length=32), nullable=True),
    sa.Column('emotion_intensity', sa.SmallInteger(), nullable=True),
    sa.Column('emotion_residual', sa.Boolean(), nullable=True),
    sa.Column('emotion_conflict_index', sa.Float(), nullable=True),
    sa.Column('lucidity_level', sa.SmallInteger(), nullable=True),
    sa.Column('vividness_level', sa.SmallInteger(), nullable=True),
    sa.Column('sensory_visual', sa.Float(), nullable=True),
    sa.Column('sensory_auditory', sa.Float(), nullable=True),
    sa.Column('sensory_tactile', sa.Float(), nullable=True),
    sa.Column('sensory_olfactory', sa.Float(), nullable=True),
    sa.Column('sensory_gustatory', sa.Float(), nullable=True),
    sa.Column('sensory_spatial', sa.Float(), nullable=True),
    sa.Column('reality_correlation', sa.SmallInteger(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('ai_processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_processing_status'), nullable=False),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_level', sa.Enum('PRIVATE', 'FRIENDS', 'PUBLIC', name='privacy_level'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('parent_dream_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dreams_emotion', 'dreams', ['user_id', 'primary_emotion', 'emotion_intensity'], unique=False)
    op.create_index('idx_dreams_quality', 'dreams', ['user_id', 'sleep_quality', 'vividness_level'], unique=False)
    op.create_index('idx_dreams_user_date', 'dreams', ['user_id', 'dream_date'], unique=False)
    op.create_index(op.f('ix_dreams_user_id'), 'dreams', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('user_insight_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auto_generate_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_generate_frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='insight_frequency'), nullable=False),
    sa.Column('preferred_day', sa.SmallInteger(), nullable=True),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('notify_on_generation', sa.Boolean(), nullable=False),
    sa.Column('notification_method', sa.Enum('EMAIL', 'PUSH', 'BOTH', name='notification_method'), nullable=False),
    sa.Column('include_trigger_analysis', sa.Boolean(), nullable=False),
    sa.Column('include_emotion_trends', sa.Boolean(), nullable=False),
    sa.Column('include_sleep_correlation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.Enum('WEEKLY', 'MONTHLY', 'PATTERN', 'RECOMMENDATION', name='insight_type'), nullable=False),
    sa.Column('time_period_start', sa.Date(), nullable=False),
    sa.Column('time_period_end', sa.Date(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_insights_user_id'), 'user_insights', ['user_id'], unique=False)
    op.create_table('dream_analysis_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('STRUCTURE', 'EMOTION', 'SYMBOL', 'INSIGHT', 'TITLE_GEN', name='analysis_task_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_processing_status'), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_analysis_tasks_dream_id'), 'dream_analysis_tasks', ['dream_id'], unique=False)
    op.create_table('dream_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('attachment_type', sa.Enum('IMAGE', 'AUDIO', 'VIDEO', 'SKETCH', name='attachment_type'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('storage_bucket', sa.Enum('PUBLIC', 'PRIVATE', name='storage_bucket'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_attachments_dream_id'), 'dream_attachments', ['dream_id'], unique=False)
    op.create_table('dream_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_embeddings_dream_id'), 'dream_embeddings', ['dream_id'], unique=True)

    # pgvector 向量列和索引 - 需要先安装 pgvector 扩展
    # 跳过失败不影响其他表的创建
    try:
        from sqlalchemy import inspect as sa_inspect
        conn = op.get_bind()
        result = conn.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'"))
        if result.fetchone():
            op.execute("CREATE EXTENSION IF NOT EXISTS vector")
            op.execute("ALTER TABLE dream_embeddings ADD COLUMN content_embedding vector(3072)")
            op.execute("""
                CREATE INDEX idx_content_embedding_hnsw
                ON dream_embeddings
                USING hnsw (content_embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64)
            """)
        else:
            print("WARNING: pgvector extension not available. Skipping vector column creation.")
            print("Install pgvector and run: ALTER TABLE dream_embeddings ADD COLUMN content_embedding vector(3072);")
    except Exception as e:
        print(f"WARNING: Could not create pgvector column: {e}")
        print("Install pgvector and run the vector migration manually.")

    op.create_table('dream_emotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('emotion_type', sa.Enum('JOY', 'SADNESS', 'FEAR', 'ANGER', 'DISGUST', 'SURPRISE', 'TRUST', 'ANTICIPATION', name='emotion_type_enum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'AI', name='emotion_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dream_id', 'emotion_type', name='uq_dream_emotion_type')
    )
    op.create_index('idx_dream_emotion_type_score', 'dream_emotions', ['dream_id', 'emotion_type', 'score'], unique=False)
    op.create_index(op.f('ix_dream_emotions_dream_id'), 'dream_emotions', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_emotions_emotion_type'), 'dream_emotions', ['emotion_type'], unique=False)
    op.create_table('dream_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('life_context', sa.Text(), nullable=True),
    sa.Column('user_interpretation', sa.Text(), nullable=True),
    sa.Column('content_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_insights_dream_id'), 'dream_insights', ['dream_id'], unique=True)
    op.create_table('dream_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_dream_id', sa.UUID(), nullable=False),
    sa.Column('target_dream_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('SIMILAR', 'CONTINUATION', 'CONTRAST', 'THEMATIC', name='relation_type'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('relation_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Enum('USER', 'AI', name='emotion_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['source_dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_dream_id', 'target_dream_id', 'relation_type', name='uq_dream_relation')
    )
    op.create_index('idx_dream_relations_source', 'dream_relations', ['source_dream_id'], unique=False)
    op.create_index('idx_dream_relations_target', 'dream_relations', ['target_dream_id'], unique=False)
    op.create_index(op.f('ix_dream_relations_source_dream_id'), 'dream_relations', ['source_dream_id'], unique=False)
    op.create_index(op.f('ix_dream_relations_target_dream_id'), 'dream_relations', ['target_dream_id'], unique=False)
    op.create_table('dream_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('intensity', sa.SmallInteger(), nullable=True),
    sa.Column('added_by', sa.Enum('USER', 'AI', name='emotion_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_symbols_dream_id'), 'dream_symbols', ['dream_id'], unique=False)
    op.create_index(op.f('ix_dream_symbols_symbol_id'), 'dream_symbols', ['symbol_id'], unique=False)
    op.create_table('dream_tags',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'tag_id')
    )
    op.create_table('dream_triggers',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'trigger_id')
    )
    op.create_index('idx_trigger_dream', 'dream_triggers', ['trigger_id', 'dream_id'], unique=False)
    op.create_table('dream_type_mappings',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Shanghai', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['dream_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'type_id')
    )
    op.create_index('idx_type_dream', 'dream_type_mappings', ['type_id', 'dream_id'], unique=False)

    # ========== 初始化种子数据 ==========

    # 插入梦境类型字典数据
    op.execute("""
        INSERT INTO dream_types (id, type_name, display_name, description, icon_emoji, usage_count) VALUES
        (gen_random_uuid(), 'NORMAL', '普通梦', '日常的梦境', '💭', 0),
        (gen_random_uuid(), 'LUCID', '清醒梦', '知道自己在做梦', '🧠', 0),
        (gen_random_uuid(), 'NIGHTMARE', '噩梦', '令人恐惧或不安', '😱', 0),
        (gen_random_uuid(), 'RECURRING', '重复梦', '之前梦到过类似的', '🔄', 0),
        (gen_random_uuid(), 'SYMBOLIC', '象征性强', '充满象征和隐喻', '🎭', 0),
        (gen_random_uuid(), 'VIVID', '特别清晰', '如同现实般清晰', '✨', 0)
    """)

    # 插入常见触发因素字典数据
    op.execute("""
        INSERT INTO triggers (id, trigger_key, display_name, category, usage_count) VALUES
        (gen_random_uuid(), 'late_night_meal', '深夜进食', 'FOOD', 0),
        (gen_random_uuid(), 'spicy_food', '辛辣食物', 'FOOD', 0),
        (gen_random_uuid(), 'alcohol', '饮酒', 'SUBSTANCE', 0),
        (gen_random_uuid(), 'caffeine', '咖啡因', 'SUBSTANCE', 0),
        (gen_random_uuid(), 'horror_movie', '恐怖片', 'ACTIVITY', 0),
        (gen_random_uuid(), 'intense_exercise', '剧烈运动', 'ACTIVITY', 0),
        (gen_random_uuid(), 'high_stress_workday', '高压工作日', 'EMOTION', 0),
        (gen_random_uuid(), 'meditation', '冥想', 'ACTIVITY', 0),
        (gen_random_uuid(), 'relationship_conflict', '关系冲突', 'EMOTION', 0),
        (gen_random_uuid(), 'sleep_deprivation', '睡眠不足', 'ENVIRONMENT', 0),
        (gen_random_uuid(), 'new_environment', '新环境', 'ENVIRONMENT', 0),
        (gen_random_uuid(), 'medication', '药物', 'SUBSTANCE', 0)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_type_dream', table_name='dream_type_mappings')
    op.drop_table('dream_type_mappings')
    op.drop_index('idx_trigger_dream', table_name='dream_triggers')
    op.drop_table('dream_triggers')
    op.drop_table('dream_tags')
    op.drop_index(op.f('ix_dream_symbols_symbol_id'), table_name='dream_symbols')
    op.drop_index(op.f('ix_dream_symbols_dream_id'), table_name='dream_symbols')
    op.drop_table('dream_symbols')
    op.drop_index(op.f('ix_dream_relations_target_dream_id'), table_name='dream_relations')
    op.drop_index(op.f('ix_dream_relations_source_dream_id'), table_name='dream_relations')
    op.drop_index('idx_dream_relations_target', table_name='dream_relations')
    op.drop_index('idx_dream_relations_source', table_name='dream_relations')
    op.drop_table('dream_relations')
    op.drop_index(op.f('ix_dream_insights_dream_id'), table_name='dream_insights')
    op.drop_table('dream_insights')
    op.drop_index(op.f('ix_dream_emotions_emotion_type'), table_name='dream_emotions')
    op.drop_index(op.f('ix_dream_emotions_dream_id'), table_name='dream_emotions')
    op.drop_index('idx_dream_emotion_type_score', table_name='dream_emotions')
    op.drop_table('dream_emotions')
    op.drop_index(op.f('ix_dream_embeddings_dream_id'), table_name='dream_embeddings')
    op.drop_table('dream_embeddings')
    op.drop_index(op.f('ix_dream_attachments_dream_id'), table_name='dream_attachments')
    op.drop_table('dream_attachments')
    op.drop_index(op.f('ix_dream_analysis_tasks_dream_id'), table_name='dream_analysis_tasks')
    op.drop_table('dream_analysis_tasks')
    op.drop_index(op.f('ix_user_insights_user_id'), table_name='user_insights')
    op.drop_table('user_insights')
    op.drop_table('user_insight_settings')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_dreams_user_id'), table_name='dreams')
    op.drop_index('idx_dreams_user_date', table_name='dreams')
    op.drop_index('idx_dreams_quality', table_name='dreams')
    op.drop_index('idx_dreams_emotion', table_name='dreams')
    op.drop_table('dreams')
    op.drop_index(op.f('ix_triggers_trigger_key'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_dream_types_type_name'), table_name='dream_types')
    op.drop_table('dream_types')

    # 尝试删除 pgvector 扩展 (可能不存在)
    try:
        op.execute("DROP EXTENSION IF EXISTS vector CASCADE")
    except Exception:
        pass
    # ### end Alembic commands ###
