"""add_user_profile_fields_bio_birthday

Revision ID: a5daccdecb55
Revises: ce115717fa40
Create Date: 2026-02-04 19:13:52.484857

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5daccdecb55'
down_revision: str | None = 'ce115717fa40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
