"""add_sleep_start_time_field

Revision ID: c352eb6f8093
Revises: 71174be6e2f5
Create Date: 2026-02-09 10:12:57.850155

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c352eb6f8093'
down_revision: str | None = '71174be6e2f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('sleep_start_time', sa.DateTime(timezone=True), nullable=True, comment='入睡时间'))
    op.alter_column('dreams', 'awakening_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='醒来时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dreams', 'awakening_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='醒来时间',
               existing_nullable=True)
    op.drop_column('dreams', 'sleep_start_time')
    # ### end Alembic commands ###
