# Generated by Django 4.2.20 on 2025-08-04 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='梦境标题')),
                ('content', models.TextField(verbose_name='梦境内容')),
                ('interpretation', models.TextField(blank=True, verbose_name='梦境解析')),
                ('personal_notes', models.TextField(blank=True, verbose_name='个人笔记')),
                ('dream_date', models.DateField(verbose_name='梦境日期')),
                ('lucidity_level', models.IntegerField(choices=[(0, '完全无意识'), (1, '轻微意识'), (2, '部分清醒'), (3, '较为清醒'), (4, '完全清醒'), (5, '超清醒状态')], default=0, verbose_name='清醒度等级')),
                ('mood_before_sleep', models.CharField(blank=True, choices=[('very_negative', '非常消极'), ('negative', '消极'), ('neutral', '中性'), ('positive', '积极'), ('very_positive', '非常积极')], max_length=20, verbose_name='睡前情绪')),
                ('mood_in_dream', models.CharField(blank=True, choices=[('very_negative', '非常消极'), ('negative', '消极'), ('neutral', '中性'), ('positive', '积极'), ('very_positive', '非常积极')], max_length=20, verbose_name='梦中情绪')),
                ('mood_after_waking', models.CharField(blank=True, choices=[('very_negative', '非常消极'), ('negative', '消极'), ('neutral', '中性'), ('positive', '积极'), ('very_positive', '非常积极')], max_length=20, verbose_name='醒后情绪')),
                ('sleep_quality', models.IntegerField(blank=True, choices=[(1, '很差'), (2, '较差'), (3, '一般'), (4, '良好'), (5, '很好')], null=True, verbose_name='睡眠质量')),
                ('sleep_duration', models.DurationField(blank=True, null=True, verbose_name='睡眠时长')),
                ('bedtime', models.TimeField(blank=True, null=True, verbose_name='就寝时间')),
                ('wake_time', models.TimeField(blank=True, null=True, verbose_name='醒来时间')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='是否重复梦')),
                ('recurring_elements', models.TextField(blank=True, verbose_name='重复元素')),
                ('vividness', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='清晰度(1-5)')),
                ('privacy', models.CharField(choices=[('private', '私人'), ('public', '公开'), ('friends', '好友可见')], default='private', max_length=10, verbose_name='隐私设置')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '梦境',
                'verbose_name_plural': '梦境',
                'ordering': ['-dream_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('normal', '普通梦境'), ('lucid', '清醒梦'), ('nightmare', '噩梦'), ('recurring', '重复梦'), ('prophetic', '预知梦'), ('healing', '治愈梦'), ('spiritual', '灵性梦境'), ('creative', '创意梦境'), ('hypnagogic', '入睡幻觉'), ('hypnopompic', '醒前幻觉'), ('sleep_paralysis', '睡眠瘫痪'), ('false_awakening', '假醒'), ('anxiety', '焦虑梦'), ('joyful', '快乐梦境'), ('melancholic', '忧郁梦境'), ('adventure', '冒险梦境')], max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('color_code', models.CharField(default='#6366f1', max_length=7, verbose_name='颜色代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '梦境分类',
                'verbose_name_plural': '梦境分类',
            },
        ),
        migrations.CreateModel(
            name='DreamJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='日记本名称')),
                ('description', models.TextField(blank=True, verbose_name='日记本描述')),
                ('color_theme', models.CharField(default='#6366f1', max_length=7, verbose_name='主题颜色')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认日记本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '梦境日记本',
                'verbose_name_plural': '梦境日记本',
            },
        ),
        migrations.CreateModel(
            name='SleepPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('bedtime', models.TimeField(verbose_name='就寝时间')),
                ('sleep_time', models.TimeField(blank=True, null=True, verbose_name='入睡时间')),
                ('wake_time', models.TimeField(verbose_name='醒来时间')),
                ('sleep_quality', models.IntegerField(choices=[(1, '很差'), (2, '较差'), (3, '一般'), (4, '良好'), (5, '很好')], verbose_name='睡眠质量')),
                ('total_sleep_time', models.DurationField(blank=True, null=True, verbose_name='总睡眠时间')),
                ('awakenings', models.PositiveIntegerField(default=0, verbose_name='夜间醒来次数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '睡眠模式',
                'verbose_name_plural': '睡眠模式',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('tag_type', models.CharField(choices=[('emotion', '情感'), ('character', '角色'), ('location', '地点'), ('object', '物体'), ('action', '行为'), ('symbol', '符号'), ('color', '颜色'), ('sound', '声音'), ('weather', '天气'), ('time', '时间'), ('custom', '自定义')], max_length=20, verbose_name='标签类型')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公共标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True, unique=True, verbose_name='图片URL')),
                ('file_key', models.CharField(max_length=500, verbose_name='OSS文件Key')),
                ('status', models.CharField(choices=[('active', '活跃'), ('pending_delete', '待删除')], default='active', max_length=20, verbose_name='状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dream.dream', verbose_name='关联梦境')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
                'ordering': ['-upload_time'],
            },
        ),
    ]
