# Generated by Django 4.2.20 on 2025-08-04 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='sleeppattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dreamjournal',
            name='dreams',
            field=models.ManyToManyField(blank=True, to='dream.dream', verbose_name='包含的梦境'),
        ),
        migrations.AddField(
            model_name='dreamjournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dream',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dream.dreamcategory', verbose_name='梦境分类'),
        ),
        migrations.AddField(
            model_name='dream',
            name='related_dreams',
            field=models.ManyToManyField(blank=True, to='dream.dream', verbose_name='相关梦境'),
        ),
        migrations.AddField(
            model_name='dream',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dream.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['user', 'status'], name='dream_uploa_user_id_7417bd_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['status', 'updated_at'], name='dream_uploa_status_947f62_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['dream', 'status'], name='dream_uploa_dream_i_a9344b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['url'], name='dream_uploa_url_c6c5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='dream_tag_tag_typ_873065_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_public'], name='dream_tag_is_publ_f597d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sleeppattern',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dreamjournal',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['user', '-dream_date'], name='dream_dream_user_id_f23988_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['privacy', '-created_at'], name='dream_dream_privacy_4b47a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['is_favorite', '-created_at'], name='dream_dream_is_favo_b5b2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['lucidity_level'], name='dream_dream_lucidit_481482_idx'),
        ),
    ]
