# Generated by Django 4.2.20 on 2025-07-16 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='图片URL')),
                ('file_key', models.CharField(max_length=500, verbose_name='OSS文件Key')),
                ('status', models.CharField(choices=[('active', '活跃'), ('pending_delete', '待删除')], default='active', max_length=20, verbose_name='状态')),
                ('marked_for_delete_time', models.DateTimeField(blank=True, null=True, verbose_name='标记删除时间')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('last_referenced_time', models.DateTimeField(auto_now=True, verbose_name='最后引用时间')),
                ('dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dream.dream', verbose_name='关联梦境')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.DeleteModel(
            name='DreamImage',
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['user', 'status'], name='dream_uploa_user_id_7417bd_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['status', 'marked_for_delete_time'], name='dream_uploa_status_c629ad_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['dream', 'status'], name='dream_uploa_dream_i_a9344b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['url'], name='dream_uploa_url_c6c5f7_idx'),
        ),
    ]
