# Generated by Django 4.2.20 on 2025-08-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='interpretation',
        ),
        migrations.AddField(
            model_name='dream',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='AI梦境解析'),
        ),
        migrations.AddField(
            model_name='dream',
            name='user_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='用户解析'),
        ),
    ]
