# Generated by Django 4.2.20 on 2025-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_uploadedimage_delete_dreamimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, unique=True, verbose_name='图片URL'),
        ),
    ]
