# Generated by Django 4.2.20 on 2025-07-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_alter_uploadedimage_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uploadedimage',
            name='dream_uploa_status_c629ad_idx',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='last_referenced_time',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='marked_for_delete_time',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['status', 'updated_at'], name='dream_uploa_status_947f62_idx'),
        ),
    ]
