# Generated by Django 4.2.20 on 2025-08-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0004_alter_uploadedimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('emotion', '情感'), ('character', '角色'), ('location', '地点'), ('object', '物体'), ('action', '行为'), ('weather', '天气')], max_length=20, verbose_name='标签类型'),
        ),
    ]
