# Generated by Django 4.2.20 on 2025-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedMemory',
        ),
    ]
