# Generated by Django 4.2.20 on 2025-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_remove_dream_interpretation_dream_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='图片URL'),
        ),
    ]
