# Generated by Django 4.2.20 on 2025-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0005_alter_tag_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='recurring_elements',
            field=models.CharField(blank=True, max_length=10, verbose_name='重复元素'),
        ),
    ]
