# Generated by Django 4.2.20 on 2025-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='备用邮箱'),
        ),
    ]
