# Generated by Django 4.2.20 on 2025-08-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dream', '0005_alter_tag_tag_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('assistant_name', models.CharField(default='梦境助手', max_length=50, verbose_name='助手名称')),
                ('personality_traits', models.JSONField(blank=True, default=dict, help_text='如：温柔、专业、幽默等', verbose_name='个性特征')),
                ('interpretation_style', models.CharField(choices=[('professional', '专业学术'), ('friendly', '亲切友好'), ('poetic', '诗意浪漫'), ('balanced', '平衡综合')], default='balanced', max_length=20, verbose_name='解读风格')),
                ('preferred_dimensions', models.JSONField(blank=True, default=list, help_text='如：心理学、象征学、生物医学等', verbose_name='偏好解读维度')),
                ('response_length', models.CharField(choices=[('concise', '简洁'), ('moderate', '适中'), ('detailed', '详细')], default='moderate', max_length=10, verbose_name='回复长度')),
                ('enable_auto_image_generation', models.BooleanField(default=False, verbose_name='自动生成梦境图像')),
                ('enable_follow_up_questions', models.BooleanField(default=True, verbose_name='启用追问功能')),
                ('enable_pattern_analysis', models.BooleanField(default=True, help_text='开启后系统会自动分析您的梦境模式并用于个性化解读', verbose_name='启用梦境模式智能分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新对话', max_length=200, verbose_name='对话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='记忆内容')),
                ('context', models.TextField(blank=True, verbose_name='上下文信息')),
                ('memory_type', models.CharField(choices=[('personal_info', '个人信息'), ('preference', '偏好设置'), ('dream_pattern', '梦境模式'), ('other', '其他')], default='other', max_length=20, verbose_name='记忆类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('embedding_id', models.CharField(blank=True, max_length=100, verbose_name='ChromaDB向量ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_memories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_services_user_id_aa80d4_idx'), models.Index(fields=['memory_type', '-created_at'], name='ai_services_memory__2c2ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '梦境助手'), ('system', '系统')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片URLs')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.chat', verbose_name='所属会话')),
                ('related_dream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dream.dream', verbose_name='关联梦境')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat', 'created_at'], name='ai_services_chat_id_3824e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at', 'is_active'], name='ai_services_user_id_7062eb_idx'),
        ),
    ]
